name: .NET
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.11

    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"

    - name: Publish nuget package
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Mirecad.Toolbox/Mirecad.Toolbox.csproj
        VERSION_STATIC: ${{env.GITVERSION_SEMVER}}
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
